
const envlocal = __dirname + '/../../../.env.local'
require('../../utility').loadEnvLocal(envlocal)

const Path = require('node:path')
const Fs = require('node:fs')

const { test, describe, afterEach } = require('node:test')
const assert = require('node:assert')
const { createLiveTransport } = require('../../live-runner')
const { runLiveEntity } = require('../../live-entity')


const { Hook0SDK, BaseFeature, stdutil, config } = require('../../..')

const {
  envOverride,
  liveClientOptions,
  liveDelay,
  makeCtrl,
  makeMatch,
  makeReqdata,
  makeStepData,
  makeValid,
} = require('../../utility')


describe('IngestedEventEntity', async () => {

  // Per-test live pacing. Delay is read from sdk-test-control.json's
  // `test.live.delayMs`; only sleeps when HOOK0_TEST_LIVE=TRUE.
  afterEach(liveDelay('HOOK0_TEST_LIVE'))

  test('instance', async () => {
    const testsdk = Hook0SDK.test()
    const ent = testsdk.IngestedEvent()
    assert(null != ent)
  })


  test('basic', async (t) => {

    
    const setup = basicSetup()
    if (setup.live) {
      return runLiveEntity(setup, {"active":true,"alias":{"field":{}},"fields":[{"active":true,"format":"uuid","name":"application_id","req":true,"short":"UUID of the application this event belongs to.","type":"`$STRING`","index$":0},{"active":true,"format":"uuid","name":"event_id","req":false,"short":"Optional unique identifier for this event (client-generated UUID).","type":"`$STRING`","index$":1},{"active":true,"name":"event_type","req":true,"short":"The type of event (e.g., 'user.created', 'order.completed').","type":"`$STRING`","index$":2},{"active":true,"name":"labels","req":true,"short":"Labels for event filtering and routing to subscriptions.","type":"`$OBJECT`","index$":3},{"active":true,"name":"metadata","req":false,"short":"Optional metadata key-value pairs associated with the event.","type":"`$OBJECT`","index$":4},{"active":true,"format":"date-time","name":"occurred_at","req":true,"short":"Timestamp when the event occurred.","type":"`$STRING`","index$":5},{"active":true,"name":"payload","req":true,"short":"The event payload.","type":"`$STRING`","index$":6},{"active":true,"name":"payload_content_type","req":true,"short":"Content type of the payload.","type":"`$STRING`","index$":7}],"name":"ingested_event","op":{"create":{"input":"data","name":"create","points":[{"active":true,"args":{},"contract":{"id":"POST /api/v1/event/","json":"{\"operationId\":\"events.ingest\",\"parameters\":[],\"protocol\":\"http\",\"requestBody\":{\"content\":{\"application/json\":{\"schema\":{\"description\":\"Event to be ingested into Hook0.\",\"properties\":{\"application_id\":{\"description\":\"UUID of the application this event belongs to.\",\"format\":\"uuid\",\"type\":\"string\"},\"event_id\":{\"description\":\"Optional unique identifier for this event (client-generated UUID). If not provided, a UUIDv7 will be generated by the server.\",\"format\":\"uuid\",\"type\":\"string\"},\"event_type\":{\"description\":\"The type of event (e.g., 'user.created', 'order.completed'). Length: 1-200 characters.\",\"type\":\"string\"},\"labels\":{\"additionalProperties\":{\"type\":\"string\"},\"description\":\"Labels for event filtering and routing to subscriptions.\",\"type\":\"object\"},\"metadata\":{\"additionalProperties\":{\"type\":\"string\"},\"description\":\"Optional metadata key-value pairs associated with the event.\",\"type\":\"object\"},\"occurred_at\":{\"description\":\"Timestamp when the event occurred.\",\"format\":\"date-time\",\"type\":\"string\"},\"payload\":{\"description\":\"The event payload. For binary content, use base64 encoding. Max length: 699050 characters (512 KiB base64-encoded).\",\"type\":\"string\"},\"payload_content_type\":{\"description\":\"Content type of the payload. Valid values: text/plain, application/json, application/octet-stream+base64. Length: 1-100 characters.\",\"type\":\"string\"}},\"required\":[\"application_id\",\"event_type\",\"labels\",\"occurred_at\",\"payload\",\"payload_content_type\"],\"type\":\"object\"}}},\"required\":true},\"responses\":{\"201\":{\"content\":{\"application/json\":{\"schema\":{\"properties\":{\"application_id\":{\"format\":\"uuid\",\"type\":\"string\"},\"event_id\":{\"format\":\"uuid\",\"type\":\"string\"},\"received_at\":{\"format\":\"date-time\",\"type\":\"string\"}},\"required\":[\"application_id\",\"event_id\",\"received_at\"],\"type\":\"object\"}}},\"description\":\"Created\"},\"400\":{\"description\":\"Bad Request\"},\"403\":{\"description\":\"Forbidden\"},\"404\":{\"description\":\"Not Found\"},\"409\":{\"description\":\"Conflict\"},\"500\":{\"description\":\"Internal Server Error\"},\"503\":{\"description\":\"Service Unavailable\"}},\"security\":[{\"biscuit\":[]}],\"securitySchemes\":{\"biscuit\":{\"description\":\"Authentication using a Biscuit token (use the format `Bearer TOKEN`)\",\"in\":\"header\",\"name\":\"Authorization\",\"type\":\"apiKey\"},\"biscuit_refresh\":{\"description\":\"Authentication using a Biscuit token of type 'refresh' (use the format `Bearer TOKEN`)\",\"in\":\"header\",\"name\":\"Authorization\",\"type\":\"apiKey\"},\"biscuit_user_access\":{\"description\":\"Authentication using a Biscuit token of type 'user_access' (use the format `Bearer TOKEN`)\",\"in\":\"header\",\"name\":\"Authorization\",\"type\":\"apiKey\"}},\"securitySource\":\"operation\"}","source":"openapi3","version":1},"kind":"http","method":"POST","orig":"/api/v1/event/","segments":[{"lit":"api"},{"lit":"v1"},{"lit":"event"}],"select":{},"transform":{"req":"`reqdata`","res":"`body`"},"index$":0}],"key$":"create"}},"relations":{"ancestors":[]},"key$":"ingested_event","name__orig":"ingested_event","Name":"IngestedEvent","name_":"ingested_event","name-":"ingested-event","NAME":"INGESTED_EVENT","index$":9}, {"active":true,"entity":"ingested_event","key$":"BasicIngestedEventFlow","kind":"basic","name":"BasicIngestedEventFlow","param":{},"step":[{"active":true,"data":{},"input":{"ref":"ingested_event_ref01"},"match":{},"op":"create","spec":[],"valid":[],"index$":0}]}, 'IngestedEvent')
    }
    const client = setup.client
    const struct = setup.struct

    const isempty = struct.isempty
    const select = struct.select


    // CREATE
    const ingested_event_ref01_ent = client.IngestedEvent()
    let ingested_event_ref01_data = setup.data.new.ingested_event['ingested_event_ref01']

    ingested_event_ref01_data = (await ingested_event_ref01_ent.create(ingested_event_ref01_data)).data()
    assert(null != ingested_event_ref01_data)


  })
})



function basicSetup(extra) {
  // TODO: fix test def options
  const options = {} // null

  // TODO: needs test utility to resolve path
  const entityDataFile =
    Path.resolve(__dirname,
      '../../../../.sdk/test/entity/ingested_event/IngestedEventTestData.json')

  // TODO: file ready util needed?
  const entityDataSource = Fs.readFileSync(entityDataFile).toString('utf8')

  // TODO: need a xlang JSON parse utility in voxgig/struct with better error msgs
  const entityData = JSON.parse(entityDataSource)

  options.entity = entityData.existing

  let client = Hook0SDK.test(options, extra)
  const struct = client.utility().struct
  const merge = struct.merge
  const transform = struct.transform

  let idmap = transform(
    ['ingested_event01','ingested_event02','ingested_event03'],
    {
      '`$PACK`': ['', {
        '`$KEY`': '`$COPY`',
        '`$VAL`': ['`$FORMAT`', 'upper', '`$COPY`']
      }]
    })

  const env = envOverride({
    'HOOK0_TEST_INGESTED_EVENT_ENTID': idmap,
    'HOOK0_TEST_LIVE': 'FALSE',
    'HOOK0_TEST_EXPLAIN': 'FALSE',
    'HOOK0_APIKEY': '',
  })

  idmap = env['HOOK0_TEST_INGESTED_EVENT_ENTID']

  const live = 'TRUE' === env.HOOK0_TEST_LIVE
  const transport = createLiveTransport()
  if (live) {
    const rawIds = process.env['HOOK0_TEST_INGESTED_EVENT_ENTID']
    idmap = rawIds && rawIds.trim() ? JSON.parse(rawIds) : {}
    if (!idmap || Array.isArray(idmap) || typeof idmap !== 'object') {
      throw new Error('Live ENTID must be a JSON object')
    }
    client = new Hook0SDK(merge([
      // FIRST, so the generated fields below win: sdk-test-control.json's
      // test.client.options adds to the live client, it does not redirect it.
      liveClientOptions(),
      {
        apikey: env.HOOK0_APIKEY,
      },
      // 'extra || {}', not a bare 'extra': struct.merge returns UNDEFINED when
      // the last entry is undefined, and basicSetup is normally called with no
      // argument at all - so a bare 'extra' silently discarded the apikey and
      // server values above and handed the SDK undefined.
      extra || {},
      { system: { fetch: transport.fetch } }
    ]))
  }

  const setup = {
    idmap,
    env,
    options,
    client,
    struct,
    data: entityData,
    explain: 'TRUE' === env.HOOK0_TEST_EXPLAIN,
    live,
    transport,
    now: Date.now(),
  }

  return setup
}
  
