// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/hook0-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"application | application_secret | applications_management | event | event_type | events_management | events_per_day_entry | health | hook0 | ingested_event | instance | login | organization | organization_edit_role | problem | quota | registration | request_attempt | response | revoke | service_token | subscription | user_authentication | user_invitation"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.Hook0SDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "hook0_list",
		Description: "List records from Hook0. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "hook0_load",
		Description: "Load a single record from Hook0. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.Hook0SDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.Hook0SDK, name string) (sdk.Hook0Entity, error) {
	switch strings.ToLower(name) {
	case "application":
		return client.Application(nil), nil
	case "application_secret":
		return client.ApplicationSecret(nil), nil
	case "applications_management":
		return client.ApplicationsManagement(nil), nil
	case "event":
		return client.Event(nil), nil
	case "event_type":
		return client.EventType(nil), nil
	case "events_management":
		return client.EventsManagement(nil), nil
	case "events_per_day_entry":
		return client.EventsPerDayEntry(nil), nil
	case "health":
		return client.Health(nil), nil
	case "hook0":
		return client.Hook0(nil), nil
	case "ingested_event":
		return client.IngestedEvent(nil), nil
	case "instance":
		return client.Instance(nil), nil
	case "login":
		return client.Login(nil), nil
	case "organization":
		return client.Organization(nil), nil
	case "organization_edit_role":
		return client.OrganizationEditRole(nil), nil
	case "problem":
		return client.Problem(nil), nil
	case "quota":
		return client.Quota(nil), nil
	case "registration":
		return client.Registration(nil), nil
	case "request_attempt":
		return client.RequestAttempt(nil), nil
	case "response":
		return client.Response(nil), nil
	case "revoke":
		return client.Revoke(nil), nil
	case "service_token":
		return client.ServiceToken(nil), nil
	case "subscription":
		return client.Subscription(nil), nil
	case "user_authentication":
		return client.UserAuthentication(nil), nil
	case "user_invitation":
		return client.UserInvitation(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
