<?php
declare(strict_types=1);

// Hook0 SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

Hook0Utility::setRegistrar(function (Hook0Utility $u): void {
    $u->clean = [Hook0Clean::class, 'call'];
    $u->done = [Hook0Done::class, 'call'];
    $u->make_error = [Hook0MakeError::class, 'call'];
    $u->feature_add = [Hook0FeatureAdd::class, 'call'];
    $u->feature_hook = [Hook0FeatureHook::class, 'call'];
    $u->feature_init = [Hook0FeatureInit::class, 'call'];
    $u->fetcher = [Hook0Fetcher::class, 'call'];
    $u->make_fetch_def = [Hook0MakeFetchDef::class, 'call'];
    $u->make_context = [Hook0MakeContext::class, 'call'];
    $u->make_options = [Hook0MakeOptions::class, 'call'];
    $u->make_request = [Hook0MakeRequest::class, 'call'];
    $u->make_response = [Hook0MakeResponse::class, 'call'];
    $u->make_result = [Hook0MakeResult::class, 'call'];
    $u->make_point = [Hook0MakePoint::class, 'call'];
    $u->make_spec = [Hook0MakeSpec::class, 'call'];
    $u->make_url = [Hook0MakeUrl::class, 'call'];
    $u->param = [Hook0Param::class, 'call'];
    $u->prepare_auth = [Hook0PrepareAuth::class, 'call'];
    $u->prepare_body = [Hook0PrepareBody::class, 'call'];
    $u->prepare_headers = [Hook0PrepareHeaders::class, 'call'];
    $u->prepare_method = [Hook0PrepareMethod::class, 'call'];
    $u->prepare_params = [Hook0PrepareParams::class, 'call'];
    $u->prepare_path = [Hook0PreparePath::class, 'call'];
    $u->prepare_query = [Hook0PrepareQuery::class, 'call'];
    $u->graphql_body = [Hook0Graphql::class, 'body'];
    $u->graphql_errors = [Hook0Graphql::class, 'errors'];
    $u->result_basic = [Hook0ResultBasic::class, 'call'];
    $u->result_body = [Hook0ResultBody::class, 'call'];
    $u->result_headers = [Hook0ResultHeaders::class, 'call'];
    $u->transform_request = [Hook0TransformRequest::class, 'call'];
    $u->transform_response = [Hook0TransformResponse::class, 'call'];
});
